// Openbare MEXC-data; geen account, API-sleutel of orderfunctionaliteit.
const MEXC = "https://api.mexc.com/api/v3", REFRESH_MS = 10_000;
const DETAIL_ASSETS = [{symbol:"BTCUSDT",name:"Bitcoin",short:"BTC"},{symbol:"ETHUSDT",name:"Ethereum",short:"ETH"},{symbol:"SOLUSDT",name:"Solana",short:"SOL"},{symbol:"XRPUSDT",name:"XRP",short:"XRP"}];
let selected=DETAIL_ASSETS[0], rankedMarkets=[], showAll=false, marketSymbols=null;
const fmt=n=>new Intl.NumberFormat("nl-NL",{style:"currency",currency:"USDT",maximumFractionDigits:n<10?4:2}).format(n);
const fetchJson=async path=>{const r=await fetch(`${MEXC}${path}`);if(!r.ok)throw new Error("MEXC marktdata is tijdelijk niet beschikbaar.");return r.json();};
function ema(v,p){const m=2/(p+1);let x=v[0];return v.map(n=>(x=n*m+x*(1-m)));} function rsi(v,p=14){const d=v.slice(1).map((n,i)=>n-v[i]);let g=d.slice(0,p).reduce((a,n)=>a+Math.max(n,0),0)/p,l=d.slice(0,p).reduce((a,n)=>a+Math.max(-n,0),0)/p,o=Array(p).fill(null);for(let i=p;i<d.length;i++){g=(g*(p-1)+Math.max(d[i],0))/p;l=(l*(p-1)+Math.max(-d[i],0))/p;o.push(l===0?100:100-100/(1+g/l));}return[null,...o];}
function detail(raw){const c=raw.map(x=>+x[4]),v=raw.map(x=>+x[5]),e20=ema(c,20),e50=ema(c,50),e200=ema(c,200),rs=rsi(c),macd=ema(c,12).map((x,i)=>x-ema(c,26)[i]),sig=ema(macd,9),i=c.length-1,va=v.slice(-20).reduce((a,n)=>a+n,0)/20,tests=[["Prijs boven EMA 20",c[i]>e20[i],20],["EMA 20 boven EMA 50",e20[i]>e50[i],20],["Prijs boven EMA 200",c[i]>e200[i],20],["RSI tussen 50 en 70",rs[i]>=50&&rs[i]<=70,15],["MACD boven signaallijn",macd[i]>sig[i],15],["Volume boven gemiddelde",v[i]>va,10]];return{close:c[i],change:(c[i]/c[i-1]-1)*100,rsi:rs[i],volumeRatio:v[i]/va,trend:c[i]>e200[i]?"Boven EMA 200":"Onder EMA 200",score:tests.reduce((a,x)=>a+(x[1]?x[2]:0),0),tests};}
const label=s=>s>=75?"Sterke context":s>=50?"Gemengde context":"Zwakke context";
function renderDetail(d){document.querySelector("#assetName").textContent=selected.name;document.querySelector("#price").textContent=fmt(d.close);const c=document.querySelector("#change");c.textContent=`${d.change>=0?"+":""}${d.change.toFixed(2)}% sinds vorige candle`;c.className=`change ${d.change>0?"positive":"negative"}`;document.querySelector("#updated").textContent=`Detail bijgewerkt: ${new Date().toLocaleTimeString("nl-NL",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}`;document.querySelector("#score").textContent=d.score;document.querySelector("#scoreRing").style.setProperty("--score",`${d.score}%`);document.querySelector("#setupLabel").textContent=label(d.score);document.querySelector("#scoreSummary").textContent=label(d.score);document.querySelector("#rsi").textContent=d.rsi.toFixed(1);document.querySelector("#volume").textContent=`${d.volumeRatio.toFixed(2)}×`;document.querySelector("#trend").textContent=d.trend;document.querySelector("#checklist").innerHTML=d.tests.map(([n,y,p])=>`<div class="check-row"><span>${n}</span><span class="check-status ${y?"yes":"no"}">${y?`✓ +${p}`:"–"}</span></div>`).join("");}
async function loadDetail(){try{renderDetail(detail(await fetchJson(`/klines?symbol=${selected.symbol}&interval=1h&limit=250`)));}catch(e){document.querySelector("#change").textContent=e.message;document.querySelector("#change").className="change neutral";}}
const num=x=>Number.isFinite(Number(x))?Number(x):0;const pct=(a,x)=>a.filter(n=>n<=x).length/a.length;
function rank(tickers,symbols){const valid=new Set(symbols.filter(x=>x.status==="1"||x.status==="ENABLED"||x.isSpotTradingAllowed).map(x=>x.symbol)),active=tickers.filter(x=>(valid.size===0||valid.has(x.symbol))&&num(x.quoteVolume)>0&&num(x.lastPrice)>0),volumes=active.map(x=>Math.log10(num(x.quoteVolume)+1));return active.map(x=>{const move=Math.abs(num(x.priceChangePercent)),range=num(x.lowPrice)>0?(num(x.highPrice)-num(x.lowPrice))/num(x.lowPrice)*100:0,liquidity=Math.min(45,pct(volumes,Math.log10(num(x.quoteVolume)+1))*45),movement=Math.min(35,move*3.5),volatility=Math.min(20,range*1.5);return{symbol:x.symbol,score:Math.round(liquidity+movement+volatility),move,quoteVolume:num(x.quoteVolume),side:num(x.priceChangePercent)>0?"Opwaarts":num(x.priceChangePercent)<0?"Neerwaarts":"Vlak"};}).sort((a,b)=>b.score-a.score||b.quoteVolume-a.quoteVolume);}
const pretty=s=>s.endsWith("USDT")?`${s.slice(0,-4)}/USDT`:s;
function renderScanner(){const q=document.querySelector("#marketSearch").value.trim().toUpperCase(),markets=rankedMarkets.filter(x=>x.symbol.includes(q)),visible=showAll?markets:markets.slice(0,30),compact=new Intl.NumberFormat("nl-NL",{notation:"compact",maximumFractionDigits:1});document.querySelector("#scanner").innerHTML=visible.length?visible.map((x,i)=>`<button class="scan-row" data-symbol="${x.symbol}"><div class="rank">${i+1}</div><div class="coin-dot">${x.symbol.slice(0,4)}</div><div class="scan-text"><strong>${pretty(x.symbol)}</strong><small>${x.side} · ${x.move.toFixed(2)}% · volume ${compact.format(x.quoteVolume)} USDT</small></div><div class="scan-score">${x.score}<small>/100</small></div></button>`).join(""):'<p class="loading">Geen markt gevonden.</p>';document.querySelectorAll(".scan-row").forEach(b=>b.addEventListener("click",()=>{const s=b.dataset.symbol;selected={symbol:s,name:pretty(s),short:s.slice(0,4)};document.querySelectorAll(".asset").forEach(x=>x.classList.remove("active"));loadDetail();window.scrollTo({top:0,behavior:"smooth"});}));}
async function scan(){const status=document.querySelector("#scanStatus");try{const tickers=await fetchJson("/ticker/24hr");if(!marketSymbols){const exchange=await fetchJson("/exchangeInfo");marketSymbols=exchange.symbols||[];}rankedMarkets=rank(tickers,marketSymbols);renderScanner();status.textContent=`${rankedMarkets.length.toLocaleString("nl-NL")} actieve markten · live`;}catch(e){status.textContent="MEXC-data niet beschikbaar";document.querySelector("#scanner").innerHTML=`<p class="loading">${e.message}</p>`;}}
function refresh(){loadDetail();scan();} document.querySelectorAll(".asset").forEach(b=>b.addEventListener("click",()=>{selected=DETAIL_ASSETS.find(x=>x.symbol===b.dataset.symbol);document.querySelectorAll(".asset").forEach(x=>x.classList.toggle("active",x===b));loadDetail();}));document.querySelector("#marketSearch").addEventListener("input",renderScanner);document.querySelector("#allMarketsButton").addEventListener("click",()=>{showAll=!showAll;document.querySelector("#allMarketsButton").textContent=showAll?"Toon top 30":"Alle markten";renderScanner();});document.querySelector("#refreshButton").addEventListener("click",refresh);refresh();window.setInterval(refresh,REFRESH_MS);if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js");
